### ISSUE TITLE
Menu icons in two columns

### ISSUE THREAD

**Issue by jurf** [FedoraQt/adwaita-qt#114]
This is Fusion in VLC:

![obrázok](https://user-images.githubusercontent.com/7472425/60575839-8f77a800-9d7c-11e9-9d27-529e56dcb050.png)

This is Adwaita-Qt:

![obrázok](https://user-images.githubusercontent.com/7472425/60575926-af0ed080-9d7c-11e9-9cd6-10dc42cd60fa.png)

Also, note that the separator height should be exactly 1px and the accelerator colour should be grey (though I’m not sure the latter is possible to do).

**Comment by grulja** [comment]
The accelerator color is wrong, I will try to fix it, as well the height of the separator, but I'm not sure about the two columns, because each menu item can have both, a checkbox and an icon and if there is an icon present, I think there should be additional column. I couldn't find a gtk app using both together to verify.

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/adwaita-qt/commit/1dd93d91a13a6473ffd3118313b8345c3d771b28 and with https://github.com/FedoraQt/adwaita-qt/commit/0cca7de29c7c6b7cf1d6db334cd55bcb3352eaf7.

Not sure whether the rows are wrong, that I will need to investigate.

**Comment by grulja** [comment]
I see this heavily used in KDE applications. I discussed this with a collegue of mine who is using Gnome and in Gnome having icons in menu items seems to be forbidden. I would personally keep it like that as in my opinion it's harmless. What do you think?
![okular](https://user-images.githubusercontent.com/1068406/60893007-62d1fd80-a260-11e9-9e60-140e6e57e7a8.png)

**Comment by jurf** [comment]
Oh, OK, so instead of using two columns, Fusion combines them, like so:

![obrázok](https://user-images.githubusercontent.com/7472425/61035041-b52d2e80-a3c6-11e9-9677-8181313cfccb.png)

Not sure if that is a good solution for Adwaita, but then there’s also the question of whether to use icons at all. I guess for proper integration it should honour the GTK settings, which by default do not show icons.

**Comment by LoganDark** [comment]
This issue still happens for me... any menus with icons (even if there are no checkboxes) have 2 columns in that spot, any menus without icons (with or without checkboxes) have only one
